### ISSUE TITLE
The copy doe snot work when the destination registry does not exist

### ISSUE THREAD

**Issue by mijamo** [dperuo/npm-carbon#5]
First, I am not sure this is the place to report errors for `@appsweet-co/npm-carbon` but I have not seen any other place to do it and the author seems to be the same so let's try!

If you try to run the script while the destination repository has not been created yet, you get:

```
==> [INFO] 📡  Getting versions from destination...
info attempt registry request try #1 at 1:30:45 PM
http request GET https://npm.pkg.github.com/@MYSCOPE/XXXXX
http 404 https://npm.pkg.github.com/@MYSCOPE/XXXXX
==> [ERROR] 💥  Error: npm package "XXXXX" does not exist under owner "YYYYYY" : XXXXX
``` 

It seems like it was handled in `npm-copy` by [an early catch of the network error](https://github.com/goodeggs/npm-copy/blob/master/src/cli.coffee#L33). I don't know why this check was removed in this fork but bringing it back might solve my issue.

**Comment by dperuo** [comment]
Hi @mijamo ! Thank you for submitting this issue. Very sorry for the slow reply. Please [upgrade to `v1.0.10`](https://www.npmjs.com/package/@appsweet-co/npm-carbon) for the fix.
